# Generated by Django 2.1.2 on 2018-11-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
