# Generated by Django 2.1.3 on 2018-12-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
