# Generated by Django 2.1.3 on 2018-12-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='motto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
