# Generated by Django 2.1.1 on 2018-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='uploaded image')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
