# Generated by Django 2.1.1 on 2018-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20181217_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('image_url', models.URLField(blank=True, max_length=400, verbose_name='image_url')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
