# Generated by Django 2.1.3 on 2018-11-24 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_friend_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('select', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('read', models.BooleanField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Notification')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
